### ISSUE TITLE
broken link http://www.singular.uni-kl.de/tutor_resol.ps in manual

### ISSUE THREAD

**Issue by dimpase** [Singular/Sources#953]
https://www.singular.uni-kl.de/Manual/latest/sing_934.htm#SEC986
mentions http://www.singular.uni-kl.de/tutor_resol.ps 

but it does not work.

**Comment by dimpase** [comment]
More precisely, it is not a link, but just the text `http://www.singular.uni-kl.de/tutor_resol.ps`.
If one makes it a hyperlink then it works. 

Also, for some reason, it's not possible to
download this file via `wget http://www.singular.uni-kl.de/tutor_resol.ps`.

Why not convert it into pdf? Then it would at least open in a modern web browser directly.

**Comment by fingolfin** [comment]
Apparently this was fixed in 62d220a725e96574e0d23628e7f3b6d66856f970 and now the link points at https://www.singular.uni-kl.de/tutor_resol.pdf which does exist.

This can be reviewed at https://www.singular.uni-kl.de/Manual/latest/sing_945.htm#SEC1002 (apparently the manual URLs are not stable ☹️ )

**Comment by dimpase** [comment]
in fact, https://www.singular.uni-kl.de/tutor_resol.pdf does exist, so all is good!
